# TODO: move this to a confige file to change while bot is running
levels = {
    "pits": {
        "1": [("keyDown", "right"), 2.6, "up"],
        "2": [("keyDown", "right"), 2, "up", 0.4, "up"],
        "3": [("keyDown", "right"), 1, "up"],
        "4": [
            ("keyDown", "right"),
            "up",
        ],
        "5": [("keyDown", "right"), 2.8, "up"],
    },
    "spikes": {
        "1": [
            ("keyDown", "right"),
            0.45,
            ("keyUp", "right"),
            0.01,
            ("keyDown", "left"),
            "up",
            1.2,
            "up",
        ],
        "2": [("keyDown", "right"), 0.5, "up", 1, "up", 1.4, "up"],
        "3": [
            ("keyDown", "right"),
            0.1,
            ("keyUp", "right"),
            1.5,
            "up",
            ("keyDown", "right"),
        ],
        "4": [
            ("keyDown", "right"),
            2.3,
            "up",
            0.3,
            "up",
            0.3,
            "up",
            0.3,
            "up",
            0.3,
            "up",
        ],
        "5": [
            ("keyDown", "left"),
            1.5,
            ("keyUp", "left"),
            ("keyDown", "right"),
            1.8,
            ("keyUp", "right"),
            0.6,
            ("keyDown", "left"),
            "up",
        ],
    },
    "push": {
        "1": [
            ("keyDown", "right"),
            1.2,
            "up",
            0.4,
            ("keyUp", "right"),
            0.8,
            ("keyDown", "left"),
            "up",
            0.2,
            ("keyUp", "left"),
            ("keyDown", "right"),
            "up",
        ],
        "2": [("keyDown", "right"), 1.8, "up"],
        "3": [("keyDown", "right"), 0.1, "up", 1.5, "up"],
        "4": [
            0.5,
            ("keyDown", "right"),
            0.4,
            ("keyUp", "right"),
            ("keyDown", "left"),
            0.2,
            "up",
            0.01,
            ("keyUp", "left"),
            ("keyDown", "right"),
            0.1,
            ("keyUp", "right"),
            2.7,
            ("keyDown", "right"),
            0.5,
            "up",
        ],
        "5": [
            ("keyDown", "left"),
            2.7,
            "up",
            0.01,
            ("keyUp", "left"),
            0.3,
            ("keyDown", "right"),
            0.3,
            ("keyUp", "right"),
            ("keyDown", "left"),
            "up",
        ],
    },
    "coins": {
        "1": [("keyDown", "right"), 2, "up"],
        "2": [("keyDown", "right"), 0.3, "up", 1.3, "up"],
        "3": [
            ("keyDown", "right"),
        ],
        "4": [
            1.3,
            ("keyDown", "right"),
            0.15,
            "up",
            0.5,
            "up",
            0.1,
            "up",
            0.1,
            "up",
            0.1,
            "up",
            0.1,
            "up",
            0.1,
            "up",
            0.1,
            "up",
            0.1,
            "up",
        ],
        "5": [
            2,
            ("keyDown", "right"),
            0.5,
            "up",
            0.5,
            "up",
            0.5,
            "up",
            # ///
            1,
            "up",
            0.5,
            "up",
            0.5,
            "up",
            # ///
            1,
            "up",
            1,
            "up",
            1,
            # jump onto last step
            "up",
            ("keyUp", "right"),
            0.5,
            ("keyDown", "right"),
            "up",
            0.8,
            "up",
            0.5,
            "up",
            0.5,
            "up",
            0.5,
            "up",
            0.8,
            ("keyUp", "right"),
            ("keyDown", "left"),
        ],
    },
    "controls": {
        "1": [
            ("keyDown", "left"),
        ],
        "2": [
            ("keyDown", "right"),
            0.2,
            "up",
            0.5,
            "up",
            0.5,
            "up",
            0.5,
            "up",
        ],
    },
    
}

door_positions = {
    "pits": (107, 485),
    "spikes": (285, 440),
    "push": (466, 452),
    "coins": (615, 534),
    "controls": (523, 679),
    "platforms": (571, 840),
    "springs": (757, 818),
    "warps": (873, 688),
    "scale": (836, 522),
    "doors": (972, 450),
    "saws": (1100, 563),
    "flappy": (1154, 738),
    "gravity": (1249, 857),
    "movement": (1413, 874),
    "wraparound": (1476, 721),
    "final": (1411, 537)
}