# TODO: move this to a confige file to change while bot is running
levels = {
    "pits": {
        "1": [("keyDown", "right"), 2.6, "up"],
        "2": [("keyDown", "right"), 2, "up", 0.4, "up"],
        "3": [("keyDown", "right"), 1, "up"],
        "4": [
            ("keyDown", "right"),
            "up",
        ],
        "5": [("keyDown", "right"), 2.8, "up"],
    },
    "spikes": {
        "1": [
            ("keyDown", "right"),
            0.45,
            ("keyUp", "right"),
            0.01,
            ("keyDown", "left"),
            "up",
            1.2,
            "up",
        ],
        "2": [("keyDown", "right"), 0.5, "up", 1, "up", 1.4, "up"],
        "3": [
            ("keyDown", "right"),
            0.1,
            ("keyUp", "right"),
            1.5,
            "up",
            ("keyDown", "right"),
        ],
        "4": [
            ("keyDown", "right"),
            2.3,
            "up",
            0.3,
            "up",
            0.3,
            "up",
            0.3,
            "up",
            0.3,
            "up",
        ],
        "5": [
            ("keyDown", "left"),
            1.5,
            ("keyUp", "left"),
            ("keyDown", "right"),
            1.8,
            ("keyUp", "right"),
            0.6,
            ("keyDown", "left"),
            "up",
            3,
        ],
    },
    "push": {
        "1": [
            ("keyDown", "right"),
            1.2,
            "up",
            0.4,
            ("keyUp", "right"),
            0.8,
            ("keyDown", "left"),
            "up",
            0.2,
            ("keyUp", "left"),
            ("keyDown", "right"),
            "up",
        ],
        "2": [("keyDown", "right"), 1.8, "up"],
        "3": [("keyDown", "right"), 0.1, "up", 1.5, "up"],
        "4": [
            0.5,
            ("keyDown", "right"),
            0.4,
            ("keyUp", "right"),
            ("keyDown", "left"),
            0.2,
            "up",
            0.01,
            ("keyUp", "left"),
            ("keyDown", "right"),
            0.1,
            ("keyUp", "right"),
            2.7,
            ("keyDown", "right"),
            0.5,
            "up",
        ],
        "5": [
            ("keyDown", "left"),
            2.7,
            "up",
            0.01,
            ("keyUp", "left"),
            0.3,
            ("keyDown", "right"),
            0.3,
            ("keyUp", "right"),
            ("keyDown", "left"),
            "up",
        ],
    },
    "coins": {
        "1": [("keyDown", "right"), 2, "up"],
        "2": [("keyDown", "right"), 0.3, "up", 1.3, "up"],
        "3": [
            ("keyDown", "right"),
        ],
        "4": [
            1.3,
            ("keyDown", "right"),
            0.15,
            "up",
            0.5,
            "up",
            0.1,
            "up",
            0.1,
            "up",
            0.1,
            "up",
            0.1,
            "up",
            0.1,
            "up",
            0.1,
            "up",
            0.1,
            "up",
        ],
        "5": [
            2,
            ("keyDown", "right"),
            0.2,
            "up",
            0.2,
            "up",
            0.1,
            "up",
            0.4,
            "up",
            0.2,
            "up",
            0.1,
            "up",
            0.18,
            "up",
            0.7,
            "up",
            0.2,
            "up",
            0.2,
            "up",
            0.2,
            "up",
            0.2,
            "up",
            0.2,
            "up",
            0.2,
            "up",
            0.2,
            "up",
            0.2,
            "up",
            0.2,
            "up",
            0.2,
            "up",
            0.2,
            "up",
            0.08,
            "up",
            0.08,
            "up",
            0.08,
            "up",
            0.08,
            "up",
            0.08,
            "up",
            0.08,
            "up",
            0.08,
            "up",
            0.08,
            "up",
            0.1,
            "up",
            0.3,
            ("keyUp", "right"),
        ],
    },
    "controls": {
        "1": [
            ("keyDown", "left"),
        ],
        "2": [
            ("keyDown", "left"),
            0.5,
            "up",
            0.5,
            "up",
            0.5,
            "up",
            0.5,
            "up",
        ],
    },
}

door_positions = {
    "pits": (155, 538),
    "spikes": (313, 493),
    "push": (495, 506),
    "coins": (627, 583),
    "controls": (541, 720),
    "platforms": (587, 865),
    "springs": (760, 847),
    "warps": (862, 725),
    "scale": (837, 574),
    "doors": (959, 504),
    "saws": (1084, 613),
    "flappy": (1128, 771),
    "gravity": (1215, 885),
    "movement": (1370, 900),
    "wraparound": (1435, 762),
}