[project]
name = "ld-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.10.0.84",
    "pillow>=11.0.0",
    "pyautogui>=0.9.54",
    "selenium>=4.28.1",
]
